# fly.toml app configuration file generated for djgbank-backend on 2023-11-23T23:03:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "djgbank-backend"
primary_region = "bog"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
